configurationset:
    - configuration:
          name: helius_config
          api_key: STEPZEN_HELIUS_API_KEY
          stepzen.queryextensionguard: true
    - configuration:
          name: shyft_config
          api_key: STEPZEN_SHYFT_API_KEY
          stepzen.queryextensionguard: true
    - configuration:
          name: hyperspace_config
          api_key: STEPZEN_HYPERSPACE_API_KEY
          stepzen.queryextensionguard: true
    - configuration:
          name: flipside_config
          api_key: STEPZEN_FLIPSIDE_API_KEY
          stepzen.queryextensionguard: true
